name: Deploy

on:
  push:
    tags:
      - "*.*.*"
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      -   run: ls -la
      -   uses: actions/checkout@master

      -   run: sudo apt-get install rsync

      -   name: Deploy theme on server
          id: deploy_theme
          uses: Pendect/action-rsyncer@v1.1.0
          env:
            DEPLOY_KEY: ${{secrets.DEPLOY_KEY}}
          with:
            flags: '-avc --delete'
            src: '.'
            dest: 'bnu@"${{secrets.SERVER_IP}}":/home/bnu/projects/reactive/www/html/'

      -   name: Display status from deploy
          run: echo "${{steps.deploy.outputs.status}}"